name: CI
on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize


jobs:
  build-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: [ '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
          tools: phpstan, phpunit
      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader
      - name: PHP Lint
        run: find src tests -name "*.php" -exec php -l {} \;
      - name: PHPStan Static Analysis
        run: phpstan
      - name: PHPUnit
        run: phpunit
